//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4
//
pub use super::game::Entity as Game;
pub use super::note::Entity as Note;
pub use super::questions::Entity as Questions;
pub use super::scope::Entity as Scope;
pub use super::user::Entity as User;
